### ISSUE TITLE
AdminLTE error using PHP 8+ and quad-zero gateway

### ISSUE THREAD

**Issue by DesktopECHO** [pi-hole/web#2562]
### Versions

  Pi-hole version is v5.16.2 (Latest: v5.16.2)
  AdminLTE version is v5.19 (Latest: v5.19)
  FTL version is v5.22 (Latest: v5.22)

### Platform:
Debian 10

### Issue:

When running a [quad-zero](https://www.cisco.com/c/en/us/support/docs/ip/routing-information-protocol-rip/16448-default.html) gateway, the API responds like so:

```
>gateway
0.0.0.0
---EOM---
```

Problem with that is, the web interface is expecting someting like:

```
>gateway
10.13.12.11 eth0
---EOM---
```

...as a result, PHP cries about the missing gateway interface, which is not such a big deal in PHP 7.4 as the web interface continutes to run.

```
mod_fastcgi.c.487) FastCGI-stderr:PHP Warning:  array_combine(): Both parameters should have an equal number of elements in /var/www/html/admin/scripts/pi-hole/php/func.php on line 638
mod_fastcgi.c.487) FastCGI-stderr:PHP Notice:  Trying to access array offset on value of type bool in /var/www/html/admin/settings.php on line 77
mod_fastcgi.c.487) FastCGI-stderr:PHP Notice:  Undefined offset: 1 in /var/www/html/admin/settings.php on line 434
mod_fastcgi.c.487) FastCGI-stderr:PHP Notice:  Undefined offset: 2 in /var/www/html/admin/settings.php on line 434
mod_fastcgi.c.487) FastCGI-stderr:PHP Notice:  Undefined offset: 1 in /var/www/html/admin/settings.php on line 435
mod_fastcgi.c.487) FastCGI-stderr:PHP Notice:  Undefined offset: 2 in /var/www/html/admin/settings.php on line 435
```

But in PHP 8.0+, arrays with a missing element are handled differently and the website glitches out with an empty settings page.

```
2023-03-26 14:25:45: (mod_fastcgi.c.421) FastCGI-stderr: PHP Fatal error:  Uncaught ValueError: array_combine(): Argument #1 ($keys) and argument #2 ($values) must have the same number of elements in /var/www/html/admin/scripts/pi-hole/php/func.php:638
2023-03-26 14:25:45: (mod_fastcgi.c.421) FastCGI-stderr: Stack trace:
2023-03-26 14:25:45: (mod_fastcgi.c.421) FastCGI-stderr: #0 /var/www/html/admin/scripts/pi-hole/php/func.php(638): array_combine()
2023-03-26 14:25:45: (mod_fastcgi.c.421) FastCGI-stderr: #1 /var/www/html/admin/settings.php(77): getGateway()
2023-03-26 14:25:45: (mod_fastcgi.c.421) FastCGI-stderr: #2 {main}
2023-03-26 14:25:45: (mod_fastcgi.c.421) FastCGI-stderr:   thrown in /var/www/html/admin/scripts/pi-hole/php/func.php on line 638
```

<img width="1219" alt="image" src="https://user-images.githubusercontent.com/33142753/227806117-a7472820-2e54-4896-97c1-2a9cbe8fa203.png">

**Comment by DesktopECHO** [comment]
Checked out `devel` and things are working as expected, thank you.
